export const menuItemsData = [
  {
    id: 1,
    name: 'Hamburguesa con papas',
    info: 'Hamburguesa acompañada con papas y complementos',
    price: 55,
    img: '/images/bigBurger.png',
  },
  {
    id: 2,
    name: 'Ensalada tipo asiatica',
    info: 'Ensalada con huevo, lechuga, fideos y verduras con aderezos',
    price: 60,
    img: '/images/bowl1.png',
  },
  {
    id: 3,
    name: 'Ensalada dulce',
    info: 'Ensalada con frutos rojos y algunas verduras con aderezos',
    price: 55,
    img: '/images/bowl2.png',
  },
  {
    id: 4,
    name: 'Pasta Bolognesa',
    info: 'Pasta con cubierta de queso mozzarela acompañada de albondigas',
    price: 50,
    img: '/images/bowl3.png',
  },
  {
    id: 5,
    name: 'Pasta butterfly',
    info: 'Pasta tipo fussilini acompañada con frutos y aderezos',
    price: 70,
    img: '/images/bowl4.png',
  },
  {
    id: 6,
    name: 'Coctel Tooty fruty',
    info: 'Coctel de frutas varias de temporada.',
    price: 45,
    img: '/images/fruits.png',
  },
  {
    id: 7,
    name: 'Tazón de cereal integal',
    info: 'Tazón de cereal integral con leche acompañado de endulzante natural',
    price: 30,
    img: '/images/granola cereal bowl.png',
  },
  {
    id: 8,
    name: 'Papas fritas',
    info: 'Papas fritas hechas al estilo francesa con complementos',
    price: 25,
    img: '/images/papasf.png',
  },
  {
    id: 9,
    name: 'Boing mango',
    info: 'Bebida nectar sabor mango',
    price: 15,
    img: '/images/boing.png',
  },
  {
    id: 10,
    name: 'Gomitas con chile',
    info: 'Gomitas agridulces empaquetadas 50 gr por bolsa',
    price: 15,
    img: '/images/gomitas.png',
  },
  {
    id: 11,
    name: 'Galletas Oreo',
    info: 'Galletas de chocolate con relleno sabor vainilla en tubo',
    price: 18,
    img: '/images/oreo.png',
  },
  {
    id: 12,
    name: 'Pollo frito',
    info: 'Pollo frito tipo mediterraneo con ensalada de vegetales',
    price: 65,
    img: '/images/kisspng-fried-chicken-lemon-chicken-chicken-meat-fine-dining-chicken-meat-5a940a1b75aa22.821205431519651355482.png',
  },
  {
    id: 13,
    name: 'Ensalada Greek',
    info: 'Ensalada tipo Greek con pescado y frutos frescos de temporada',
    price: 24,
    img: '/images/kisspng-greek-salad-fruit-salad-spinach-salad-muesli-vegetable-salad-5a96f429ce9af3.7299622115198423458463.png',
  },
  {
    id: 14,
    name: 'Sandwich',
    info: 'Sandwich de jamon de pavo, pierna o milanesa con lechuga, cebolla, jitomate y aderezos',
    price: 24,
    img: '/images/sandwich.png',
  },
  {
    id: 15,
    name: 'Brownies de chocolate',
    info: 'Brownies de chocolate con relleno de avellanas amargas con cubierta de cacahuate',
    price: 17,
    img: '/images/Brownies.png',
  },
  {
    id: 16,
    name: 'Agua natural',
    info: 'Agua natural enbotellada presentación 1 litro marca Ciel',
    price: 18,
    img: '/images/Agua.png',
  },
  // {
  //   id: 17,
  //   name: 'Pizza',
  //   info: 'spicey with garlic and then deep fried to crispy perfection',
  //   price: 24,
  //   img: '/images/pizza.png',
  // },
];
